In [1]:
import csv
import numpy as ny

In [8]:
data = []
with open(r"C:\Users\rabin\Downloads\MER_T07_02A-2020-02-03 (5).csv", 'r') as csvfile:
    file_reader=csv.reader(csvfile, delimiter=',')
    for row in file_reader:
        data.append(row)
data=ny.array(data)
data

array([['MSN', 'YYYYMM', 'Value', 'Column_Order', 'Description', 'Unit'],
       ['CLETPUS', '194913', '135451.32', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ['CLETPUS', '195013', '154519.994', '1',
        'Electricity Net Generation From Coal, All Sectors',
        'Million Kilowatthours'],
       ...,
       ['ELETPUS', '201908', '401363.186', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201909', '359300.603', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours'],
       ['ELETPUS', '201910', '321921.812', '13',
        'Electricity Net Generation Total (including from sources not shown), All Sectors',
        'Million Kilowatthours']], dtype='<U80')

In [9]:
#  Explore the important attributes like dimension,shape, data type etc, of the array formed.
print(f"The shape of the array is {ny.shape(data)}")
print(f"The dimension of the array is {ny.ndim(data)}")
print(f"The data type of the array is {data.dtype}")

The shape of the array is (8217, 6)
The dimension of the array is 2
The data type of the array is <U80


In [11]:
# Print the data contained in the first 10 rows of the 4th column.
print(data[:10, 3])

['Column_Order' '1' '1' '1' '1' '1' '1' '1' '1' '1']


In [13]:
# Which row serves as the headers/titles for all the columns.
print(data[0:1,0:6:4])

[['MSN' 'Description']]


In [14]:
# Print the data contained in column 2 and 3 from row 1 till row 20.
print(data[1:21, 2:4])

[['135451.32' '1']
 ['154519.994' '1']
 ['185203.657' '1']
 ['195436.666' '1']
 ['218846.325' '1']
 ['239145.966' '1']
 ['301362.698' '1']
 ['338503.484' '1']
 ['346386.207' '1']
 ['344365.781' '1']
 ['378424.21' '1']
 ['403067.357' '1']
 ['421870.669' '1']
 ['450249.238' '1']
 ['493926.719' '1']
 ['526230.019' '1']
 ['570925.951' '1']
 ['613474.8' '1']
 ['630483.363' '1']
 ['684904.58' '1']]


In [21]:
# Print the data present in only the first three and the last three rows of all the columns in a single output.
print(data[:3, :])
print(data[-3:, :])

[['MSN' 'YYYYMM' 'Value' 'Column_Order' 'Description' 'Unit']
 ['CLETPUS' '194913' '135451.32' '1'
  'Electricity Net Generation From Coal, All Sectors'
  'Million Kilowatthours']
 ['CLETPUS' '195013' '154519.994' '1'
  'Electricity Net Generation From Coal, All Sectors'
  'Million Kilowatthours']]
[['ELETPUS' '201908' '401363.186' '13'
  'Electricity Net Generation Total (including from sources not shown), All Sectors'
  'Million Kilowatthours']
 ['ELETPUS' '201909' '359300.603' '13'
  'Electricity Net Generation Total (including from sources not shown), All Sectors'
  'Million Kilowatthours']
 ['ELETPUS' '201910' '321921.812' '13'
  'Electricity Net Generation Total (including from sources not shown), All Sectors'
  'Million Kilowatthours']]


In [32]:
# Sort the data on the basis of net amount of electricity generated irrespective of the source.
a=data[1:,2:3]
b = ny.where(a == 'Not Available')
print(b)
c=b.astype(float)
sorted_data = data[data[:, c].argsort()]
print(sorted_data)

(array([1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906,
       1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917,
       1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928,
       1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939,
       1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950,
       1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961,
       1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972,
       1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983,
       1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994,
       1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
       2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016,
       2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027,
       2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035, 2036, 2037, 2038,
       2039, 2040, 2041, 2042, 2043, 2044, 2045, 2

AttributeError: 'tuple' object has no attribute 'astype'

In [38]:
a=data[1:,2:3]
b = ny.where(a == 'Not Available')
print(b)
c=b.astype(float)
d=sum(c)
d

(array([1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906,
       1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917,
       1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928,
       1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939,
       1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950,
       1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961,
       1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972,
       1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983,
       1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994,
       1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
       2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016,
       2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027,
       2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035, 2036, 2037, 2038,
       2039, 2040, 2041, 2042, 2043, 2044, 2045, 2

AttributeError: 'tuple' object has no attribute 'astype'

In [40]:
# Print the Total Energy generated in the USA till date.
a=data[1:,2:3]
b = ny.where(a == 'Not Available')
print(b)
c=b.astype(float)
d=sum(c)
d

(array([1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906,
       1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917,
       1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928,
       1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939,
       1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950,
       1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961,
       1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972,
       1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983,
       1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994,
       1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
       2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016,
       2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027,
       2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035, 2036, 2037, 2038,
       2039, 2040, 2041, 2042, 2043, 2044, 2045, 2

AttributeError: 'tuple' object has no attribute 'astype'