In [1]:
import numpy as ny

In [6]:
# Create a 1D array of numbers from 0 to 9.
a1=ny.arange(0,10)
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
# Extract all odd numbers from the array created in ques 1.
mask_odd=a1%2!=0
a1[mask_odd]

array([1, 3, 5, 7, 9])

In [11]:
# Replace all odd numbers in the array created in ques 1 with 100.
a1[a1%2!=0]=100
print(a1)

[  0 100   2 100   4 100   6 100   8 100]


In [ ]:
# Replace all odd numbers in array in ques 1  with 1 without changing the actual array values.
a2=a1.copy()
a2[a2%2!=0]=1
print(a2)

In [20]:
# Declare a 1D array and then convert it to a 2D array with 2 rows.
a3=ny.arange(1,9).reshape(2,4)
a3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
# Get the positions where elements are even in the array declared in ques 1.
a4=ny.argsort(a1)
a4

array([0, 2, 4, 6, 8, 1, 3, 5, 7, 9], dtype=int64)

In [24]:
# Declare and Reverse the rows of a 2D array.
a5=ny.arange(1,9).reshape(2,4)
a5[::-1]

array([[5, 6, 7, 8],
       [1, 2, 3, 4]])

In [33]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10 by using the following code snippet and then find its mean, median, standard deviation.
a6=ny.random.uniform(5,10,size=(5,3))
mean=ny.mean(a6)
median=ny.median(a6)
std=ny.std(a6)
print(mean,"\n",median,"\n",std)

7.391500368499787 
 6.6837984570177245 
 1.6172214800175528


In [38]:
# Create and find the 5th and 95th percentile of an array that contains scores of toppers in four subjects, taken from three different branches of engineering
a7=ny.random.randint(1,12,size=12).reshape(3,4)
per5=ny.percentile(a7,5)
per95=ny.percentile(a7,95)
print(per5,"\n",per95)

1.0 
 9.899999999999999


In [44]:
# From the array A,replace all values greater than 30 to 30 and less than 10 to 10.
ny.random.seed(100)
a8=ny.random.uniform(1,50,20)
mask_30=a8>30
a8[mask_30]=30
mask_10=a8<10
a8[mask_10]=10
print(a8)

[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]


In [51]:
# Get the positions of top 5 maximum values in the array A generated in ques 13.
a9=ny.argsort(a8)
max_value=a9[(a9>=5)]
print(max_value)

[17  5 13  8 12 11 14 19  9 18  7  6 15 16 10]


In [54]:
# Convert array_of_arrays(2-D array) into a flat linear 1d array.
b1=ny.arange(1,13).reshape(3,4)
b1.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [59]:
# Compute the maximum for each row.
ny.random.seed(100)
b2=ny.random.randint(1,10,[5,3])
max=b2.max(axis=0)
print(max)

[9 9 9]


In [60]:
# Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers.
b3=ny.arange(5,35,3)
print(b3)
len(b3)

[ 5  8 11 14 17 20 23 26 29 32]


10

In [64]:
# Slice the array to get the first two rows and columns.
b4=ny.array([[1,3,5,7],[9,11,13,15],[2,4,6,8]])
b4[0:2,0:2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
# Create a 2-D array of shape (3,4), populate it with random integers and then sort it using fancy indexing.
b5=ny.random.randint(1,12,size=12).reshape(3,4)
fancy=ny.argsort(b5)
b5[fancy]

In [69]:
# Get all items between 5 and 10 from an array A with elements [2, 6, 1, 9, 10, 3, 27].
b6=ny.array([2,6,1,9,10,3,27])
b7=b6[(b6>=5)&(b6<=10)]
b7

array([ 6,  9, 10])